# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AffiniPay | Developers
email: devsupport@affinipay.com
description: Developer documentation for AffiniPay, LawPay, CPACharge, and MedPay integration developers.

#baseurl: "/docs" # the subpath of your site, e.g. /blog ===This seems to break the scrollspy functionality===

# The base hostname & protocol for your site
production_url: "https://developers.affinipay.com"
qa_url: "https://docs.qa.affinipay.com"

# Google services
google_analytics: UA-17701891-1

# Build settings
markdown: kramdown

lunr_search:
  excludes: header.html

exclude:
  - .git
  - gulp
  - node_modules
  - .DS_Store
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - Rakefile
  - README.md
